spring:
   datasource:
      url: jdbc:mariadb://localhost:3317/conexa?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: 4380
      driver-class-name: org.mariadb.jdbc.Driver
   jpa:
      database-platform: org.hibernate.dialect.MariaDBDialect
      show-sql: false
      hibernate:
         ddl-auto: update