spring:
   datasource:
      url: jdbc:mariadb://localhost:3317/conexa
      username: root
      password: 4380
      driver-class-name: org.mariadb.jdbc.Driver
      hikari:
         maximum-pool-size: 10
   jpa:
      database-platform: org.hibernate.dialect.MariaDBDialect
      show-sql: true
      hibernate:
         ddl-auto: update
   autoconfigure:
      exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
jwt:
   secret: conexa
   expiration: 86400
logging:
   level:
      root: INFO
      org.springframework: INFO
      org.hibernate: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      com.zaxxer.hikari: DEBUG